from enum import auto, Enum

class EventType(Enum):
    SERVER_SHUTDOWN         = auto()
    SERVER_COMMAND          = auto()
    CLIENT_CONNECTED        = auto()
    CLIENT_DISCONNECTED     = auto()
    CLIENT_MESSAGE          = auto()
    SEND_MESSAGE            = auto()
    AUTH_GROUP              = auto()
    AUTH_PROJECT            = auto()
    GROUP_CREATE            = auto()
    GROUP_DELETE            = auto()
    GROUP_TRANSFER          = auto()
    GROUP_ADD               = auto()
    GROUP_REMOVE            = auto()
    GROUP_LEAVE             = auto()
    GROUP_INFO              = auto()
    GROUP_LIST              = auto()
    INVENTORY_ADD           = auto()
    INVENTORY_REMOVE        = auto()
    ITEM_GET                = auto()
    ITEM_ADD                = auto()
    ITEM_REMOVE             = auto()
    ITEM_DELETE             = auto()
    ITEM_TRANSFER           = auto()
    PROJECT_VIEW_ALL        = auto()
    PROJECT_VIEW_ONE        = auto()
    PROJECT_CREATE          = auto()
    PROJECT_DELETE          = auto()
    PROJECT_TRANSFER        = auto()
    PROJECT_SCOPE           = auto()
    PROJECT_ITEM_TRACK      = auto()
    PROJECT_ITEM_DELETE     = auto()
    PROJECT_ITEM_ADD        = auto()
    PROJECT_ITEM_REMOVE     = auto()
    PROJECT_ITEM_RESERVE    = auto()
    PROJECT_ITEM_RELEASE    = auto()